---
apiVersion: template.openshift.io/v1
kind: Template
objects:

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    labels:
      app: nodejs-mongo-persistent
      template: nodejs-mongo-persistent
    name: nodejs-mongo-persistent
  spec:
    lookupPolicy:
      local: false
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    labels:
      app: nodejs-mongo-persistent
      template: nodejs-mongo-persistent
    name: sample-app

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    labels:
      app: nodejs-mongo-persistent
      template: nodejs-mongo-persistent
    name: sample-app
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'sample-app:1.0'
    postCommit:
      script: npm test
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: 'https://github.com/poornima-sivanand/nodejs-ex.git'
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: NPM_MIRROR
        from:
          kind: ImageStreamTag
          name: 'nodejs:12'
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
      - imageChange:
        type: ImageChange
      - type: ConfigChange